//! Cyclotomic integer coefficients `CycInt` = ℤ[ζ]/(Φ_n(ζ)).
//!
//! Elements are integer polynomials in ζ = ζ_n = e^{2πi/n}, reduced modulo the
//! n-th cyclotomic polynomial Φ_n. This is the coefficient ring that lets us
//! build the dihedral root systems I₂(m) for every m ≥ 3, including the values
//! m ∉ {3,4,5,6} that need neither ℤ nor ℤ[φ].
//!
//! # Correspondence with PyCox
//!
//! This mirrors PyCox's `lpolmod` / `rootof1` machinery (`pycox_ref.py`,
//! `cyclpol` ≈857, `lpolmod` ≈874–1141, `rootof1` ≈1141, `ir` ≈1167). PyCox
//! works in the field generated by `E(m) = ζ_m` with modulus `Φ_m`; we match
//! that exactly (so the reduced Cartan entries come out byte-for-byte the same
//! as PyCox's `cartanmat("I?", 2)`).
//!
//! # Sentinel ring (rational constants)
//!
//! `RootCoeff::from_int`/`zero` cannot know which cyclotomic field they belong
//! to, so a constant carries the sentinel order `n = 0`, meaning "a plain
//! rational integer, promotable to any field". Every binary operation promotes
//! a sentinel operand to the other operand's field; combining two sentinels
//! stays a sentinel. Within a single root system every non-constant value
//! originates from a Cartan entry, so all real operands share one `n`.
//!
//! # Sign / ordering precision
//!
//! The root-coordinate values that actually arise are tiny algebraic integers
//! (`|coeff| ≤ 2`, height < the Coxeter number). The minimal separation between
//! distinct such values evaluated at ζ_n is far larger than f64 rounding error,
//! so [`CycInt::approx`] and [`CycInt::is_nonneg`] using f64 evaluation of the
//! real part are exact for the (height, rev-lex) root sort. PyCox itself orders
//! these roots with float comparisons (`lpolmod.__gt__`).

use std::f64::consts::PI;

use super::RootCoeff;

/// Sentinel cyclotomic order: a plain rational integer not yet bound to a
/// cyclotomic field. Promoted to the partner's order on first combination.
const SENTINEL: u32 = 0;

/// An element of ℤ[ζ]/(Φ_n(ζ)), with ζ = ζ_n = e^{2πi/n}.
///
/// Invariants (upheld by [`CycInt::new`]):
/// - `coeffs.len() <= deg(Φ_n) = φ(n)` (Euler totient), or `coeffs` is empty;
/// - trailing zeros are trimmed (so the value `0` is the empty vector);
/// - `n == 0` ([`SENTINEL`]) iff the value is a rational constant.
///
/// # Equality and hashing
///
/// `PartialEq`/`Eq`/`Hash` are *value*-based, not representation-based. A
/// rational constant (e.g. `from_int(1)`, order [`SENTINEL`]) compares and
/// hashes equal to the same constant carried in any cyclotomic field
/// (`CycInt::new(7, vec![1])`). This is required because the root-system BFS
/// stores `Vec<CycInt>` keys that mix sentinel constants (from `from_int`/
/// `zero`) with field-bound values (from Cartan entries): the *value* `1` must
/// be one key regardless of how it was produced. The field order `n` only
/// participates in the key for genuinely non-constant values
/// (`coeffs.len() > 1`); within one root system only a single field is present,
/// so distinct fields never alias.
#[derive(Clone, Debug)]
pub struct CycInt {
    /// Cyclotomic order n (ζ = ζ_n). `0` marks a rational constant (sentinel).
    n: u32,
    /// Coefficients of the reduced polynomial, low degree first; trailing zeros
    /// trimmed. Length ≤ φ(n).
    coeffs: Vec<i64>,
}

impl PartialEq for CycInt {
    fn eq(&self, other: &Self) -> bool {
        if self.coeffs != other.coeffs {
            return false;
        }
        // Constants (deg ≤ 0) are equal regardless of their field tag; genuine
        // field elements must also agree on the field order.
        if self.coeffs.len() <= 1 {
            true
        } else {
            self.n == other.n
        }
    }
}

impl Eq for CycInt {}

impl std::hash::Hash for CycInt {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.coeffs.hash(state);
        // Mirror `eq`: only fold the field order in for non-constant values so
        // a constant hashes identically whether sentinel or field-bound.
        if self.coeffs.len() > 1 {
            self.n.hash(state);
        }
    }
}

impl CycInt {
    /// Build `Σ coeffs[i]·ζ_n^i` reduced modulo Φ_n.
    ///
    /// `n` must be ≥ 1 (a genuine cyclotomic order) or the [`SENTINEL`] value
    /// `0` for a rational constant. For a sentinel, `coeffs` must have length
    /// ≤ 1 (a bare integer).
    ///
    /// # Panics
    /// Panics if `n == SENTINEL` but `coeffs` encodes a non-constant value.
    pub fn new(n: u32, coeffs: Vec<i64>) -> Self {
        if n == SENTINEL {
            let c = trim(coeffs);
            assert!(
                c.len() <= 1,
                "sentinel CycInt must be a constant, got coeffs {c:?}"
            );
            return Self { n, coeffs: c };
        }
        let phi = Self::phi(n);
        let reduced = reduce_mod(coeffs, &phi);
        Self { n, coeffs: reduced }
    }

    /// The primitive root of unity ζ_n itself.
    pub fn zeta(n: u32) -> Self {
        assert!(n >= 1, "zeta order must be ≥ 1");
        Self::new(n, vec![0, 1])
    }

    /// `2·cos(π/m) = ζ_{2m} + ζ_{2m}^{-1}`, living in the field of order `2m`.
    ///
    /// `ζ_{2m}^{-1} ≡ ζ_{2m}^{2m-1}` because ζ_{2m}^{2m} = 1.
    pub fn two_cos_pi_over_m(m: u32) -> Self {
        assert!(m >= 1, "two_cos_pi_over_m needs m ≥ 1");
        let n = 2 * m;
        let zeta = Self::zeta(n);
        let zeta_inv = Self::new(n, unit_pow(n - 1, n));
        zeta.add(&zeta_inv)
    }

    /// The order n of the cyclotomic field (`0` for a rational constant).
    pub fn order(&self) -> u32 {
        self.n
    }

    /// Borrow the reduced coefficient vector (low degree first, trimmed).
    pub fn coeffs(&self) -> &[i64] {
        &self.coeffs
    }

    /// Integer coefficients of the n-th cyclotomic polynomial Φ_n, low degree
    /// first; the polynomial is monic of degree φ(n) so the last entry is `1`.
    ///
    /// Port of PyCox `cyclpol(n, u)`: start from `x^n − 1`, then divide out
    /// Φ_d for every proper divisor d of n (smallest first via the recursion).
    /// All arithmetic is exact integer polynomial division.
    pub fn phi(n: u32) -> Vec<i64> {
        assert!(n >= 1, "Φ_n needs n ≥ 1");
        if n == 1 {
            // Φ_1 = x − 1
            return vec![-1, 1];
        }
        // f = (x^n − 1) / (x^m − 1) for the largest proper divisor m of n.
        let mut m = n / 2;
        while n % m != 0 {
            m -= 1;
        }
        let mut f = exact_div(&x_pow_minus_one(n), &x_pow_minus_one(m));
        // Divide out Φ_d for proper divisors d of n that do not divide m.
        for d in 1..n {
            if n % d == 0 && m % d != 0 {
                f = exact_div(&f, &Self::phi(d));
            }
        }
        f
    }

    /// Evaluate the real part at ζ_n = e^{2πi/n} as an f64.
    fn eval_real(&self) -> f64 {
        if self.coeffs.is_empty() {
            return 0.0;
        }
        if self.n == SENTINEL {
            // A constant: its real value is coeffs[0].
            return self.coeffs[0] as f64;
        }
        let theta = 2.0 * PI / self.n as f64;
        self.coeffs
            .iter()
            .enumerate()
            .map(|(k, &c)| c as f64 * (theta * k as f64).cos())
            .sum()
    }
}

// ---------------------------------------------------------------------------
// Field-promotion helpers
// ---------------------------------------------------------------------------

/// Resolve the common cyclotomic order of two operands, promoting a sentinel
/// (order 0) to the partner's order.
///
/// # Panics
/// Panics if both operands carry distinct non-sentinel orders — that would mean
/// mixing two different cyclotomic fields, which never happens inside a single
/// root system.
fn common_order(a: &CycInt, b: &CycInt) -> u32 {
    match (a.n, b.n) {
        (SENTINEL, SENTINEL) => SENTINEL,
        (SENTINEL, x) | (x, SENTINEL) => x,
        (x, y) if x == y => x,
        (x, y) => panic!("cannot combine CycInt of order {x} with order {y}"),
    }
}

// ---------------------------------------------------------------------------
// Polynomial helpers (free functions, all exact integer arithmetic)
// ---------------------------------------------------------------------------

/// Drop trailing zero coefficients (canonicalises the zero polynomial to `[]`).
fn trim(mut c: Vec<i64>) -> Vec<i64> {
    while c.last() == Some(&0) {
        c.pop();
    }
    c
}

/// Dense coefficients of `x^n − 1`, low degree first.
fn x_pow_minus_one(n: u32) -> Vec<i64> {
    let mut v = vec![0_i64; n as usize + 1];
    v[0] = -1;
    v[n as usize] = 1;
    v
}

/// Exact polynomial division `num / den` (low degree first). `den` must be
/// monic-ish with non-zero leading coefficient and divide `num` exactly.
///
/// # Panics
/// Panics if the division leaves a non-zero remainder (a programming error: the
/// cyclotomic recursion only ever performs exact divisions).
fn exact_div(num: &[i64], den: &[i64]) -> Vec<i64> {
    let den = trim(den.to_vec());
    assert!(!den.is_empty(), "division by zero polynomial");
    let mut rem = trim(num.to_vec());
    let dd = den.len() - 1; // degree of denominator
    let lead = *den.last().unwrap();
    if rem.len() <= dd {
        // num has lower degree than den; quotient is 0 only if num is 0.
        assert!(rem.is_empty(), "exact_div: non-zero remainder (degree)");
        return Vec::new();
    }
    let mut quot = vec![0_i64; rem.len() - dd];
    while rem.len() > dd {
        let rd = rem.len() - 1; // degree of current remainder
        let shift = rd - dd;
        let top = *rem.last().unwrap();
        assert!(
            top % lead == 0,
            "exact_div: non-divisible leading coefficient {top} by {lead}"
        );
        let factor = top / lead;
        quot[shift] = factor;
        for (i, &dc) in den.iter().enumerate() {
            rem[shift + i] -= factor * dc;
        }
        rem = trim(rem);
        if rem.len() <= dd {
            break;
        }
    }
    assert!(rem.is_empty(), "exact_div: non-zero remainder {rem:?}");
    trim(quot)
}

/// Reduce `coeffs` (low degree first, arbitrary length) modulo the monic
/// polynomial `phi` (degree φ(n), leading coefficient 1). Returns a trimmed
/// vector of degree < deg(phi).
fn reduce_mod(coeffs: Vec<i64>, phi: &[i64]) -> Vec<i64> {
    let d = phi.len() - 1; // deg(Φ_n)
    debug_assert_eq!(*phi.last().unwrap(), 1, "Φ_n must be monic");
    let mut c = trim(coeffs);
    while c.len() > d {
        let top = *c.last().unwrap();
        let shift = c.len() - 1 - d; // = deg(c) − d
                                     // Subtract top · x^shift · Φ_n (monic ⇒ no division needed).
        for (i, &pc) in phi.iter().enumerate() {
            c[shift + i] -= top * pc;
        }
        c = trim(c);
    }
    c
}

/// Dense coefficients of the monomial `ζ^k` (reduced via ζ^n = 1 first), i.e.
/// `x^(k mod n)`, low degree first. Used to build inverse powers ζ^{-1} = ζ^{n-1}.
fn unit_pow(k: u32, n: u32) -> Vec<i64> {
    let e = (k % n) as usize;
    let mut v = vec![0_i64; e + 1];
    v[e] = 1;
    v
}

// ---------------------------------------------------------------------------
// RootCoeff impl
// ---------------------------------------------------------------------------

impl RootCoeff for CycInt {
    fn zero() -> Self {
        Self {
            n: SENTINEL,
            coeffs: Vec::new(),
        }
    }

    fn from_int(n: i64) -> Self {
        if n == 0 {
            return <Self as RootCoeff>::zero();
        }
        Self {
            n: SENTINEL,
            coeffs: vec![n],
        }
    }

    fn add(&self, o: &Self) -> Self {
        let order = common_order(self, o);
        let len = self.coeffs.len().max(o.coeffs.len());
        let mut c = vec![0_i64; len];
        for (i, &x) in self.coeffs.iter().enumerate() {
            c[i] += x;
        }
        for (i, &x) in o.coeffs.iter().enumerate() {
            c[i] += x;
        }
        // Already within degree bounds when orders match; new() re-reduces and
        // re-trims (and validates the sentinel-constant case).
        CycInt::new(order, c)
    }

    fn sub(&self, o: &Self) -> Self {
        self.add(&o.neg())
    }

    fn mul(&self, o: &Self) -> Self {
        let order = common_order(self, o);
        if self.coeffs.is_empty() || o.coeffs.is_empty() {
            return CycInt::new(order, Vec::new());
        }
        // Convolution, then reduce mod Φ (new() handles reduction).
        let mut conv = vec![0_i64; self.coeffs.len() + o.coeffs.len() - 1];
        for (i, &a) in self.coeffs.iter().enumerate() {
            if a == 0 {
                continue;
            }
            for (j, &b) in o.coeffs.iter().enumerate() {
                conv[i + j] += a * b;
            }
        }
        CycInt::new(order, conv)
    }

    fn neg(&self) -> Self {
        Self {
            n: self.n,
            coeffs: self.coeffs.iter().map(|&c| -c).collect(),
        }
    }

    fn is_zero(&self) -> bool {
        self.coeffs.is_empty()
    }

    fn is_nonneg(&self) -> bool {
        // See module-level precision note: f64 real-part evaluation is exact for
        // the tiny algebraic integers that arise as root coordinates.
        if self.coeffs.is_empty() {
            return true;
        }
        if self.n == SENTINEL {
            return self.coeffs[0] >= 0;
        }
        self.eval_real() >= 0.0
    }

    fn approx(&self) -> f64 {
        self.eval_real()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -- Φ_n computation (port of PyCox cyclpol) -----------------------------

    #[test]
    fn phi_small() {
        // Φ_1 = x − 1
        assert_eq!(CycInt::phi(1), vec![-1, 1]);
        // Φ_2 = x + 1
        assert_eq!(CycInt::phi(2), vec![1, 1]);
        // Φ_3 = x² + x + 1
        assert_eq!(CycInt::phi(3), vec![1, 1, 1]);
        // Φ_4 = x² + 1
        assert_eq!(CycInt::phi(4), vec![1, 0, 1]);
    }

    #[test]
    fn phi_14_for_i7() {
        // Φ_14 = x⁶ − x⁵ + x⁴ − x³ + x² − x + 1
        assert_eq!(CycInt::phi(14), vec![1, -1, 1, -1, 1, -1, 1]);
    }

    #[test]
    fn phi_16_for_i8() {
        // Φ_16 = x⁸ + 1
        assert_eq!(CycInt::phi(16), vec![1, 0, 0, 0, 0, 0, 0, 0, 1]);
    }

    #[test]
    fn phi_7_and_8() {
        // Φ_7 = 1 + x + … + x⁶  (used as the I7 modulus by PyCox)
        assert_eq!(CycInt::phi(7), vec![1, 1, 1, 1, 1, 1, 1]);
        // Φ_8 = x⁴ + 1  (used as the I8 modulus by PyCox)
        assert_eq!(CycInt::phi(8), vec![1, 0, 0, 0, 1]);
    }

    // -- two_cos_pi_over_m approx --------------------------------------------

    #[test]
    fn two_cos_pi_over_7_approx() {
        let v = CycInt::two_cos_pi_over_m(7);
        assert!(
            (v.approx() - 1.8019377358048383).abs() < 1e-12,
            "got {}",
            v.approx()
        );
    }

    #[test]
    fn two_cos_pi_over_8_approx() {
        let v = CycInt::two_cos_pi_over_m(8);
        assert!(
            (v.approx() - 1.8477590650225735).abs() < 1e-12,
            "got {}",
            v.approx()
        );
    }

    // -- zeta / reduction roundtrip ------------------------------------------

    #[test]
    fn zeta_pow_n_is_one() {
        // ζ_n^n ≡ 1 (mod Φ_n) for several n.
        for n in [5_u32, 7, 8, 12, 16] {
            let zeta = CycInt::zeta(n);
            let mut acc = CycInt::from_int(1);
            for _ in 0..n {
                acc = acc.mul(&zeta);
            }
            assert_eq!(acc, CycInt::from_int(1), "ζ_{n}^{n} should be 1");
        }
    }

    #[test]
    fn zeta_inv_equals_zeta_n_minus_1() {
        // ζ^{-1} · ζ = 1, with ζ^{-1} built as ζ^{n-1}.
        for n in [7_u32, 8, 16] {
            let zeta = CycInt::zeta(n);
            let zeta_inv = CycInt::new(n, super::unit_pow(n - 1, n));
            assert_eq!(zeta.mul(&zeta_inv), CycInt::from_int(1));
        }
    }

    #[test]
    fn mul_reduction_roundtrip() {
        // (ζ_7^3 + ζ_7^4) is the I7 off-diagonal entry; squaring then comparing
        // with an independent f64 evaluation must agree.
        let e = CycInt::new(7, vec![0, 0, 0, 1, 1]);
        let sq = e.mul(&e);
        // 2cos(2π·3/7) + 2cos(2π·4/7) ... easier: just check approx consistency:
        // (ζ^3+ζ^4) numerically and its square.
        let approx_e = e.approx();
        let approx_sq = sq.approx();
        assert!((approx_sq - approx_e * approx_e).abs() < 1e-9);
    }

    // -- Φ-degree bound ------------------------------------------------------

    #[test]
    fn reduced_degree_below_totient() {
        // Build a high-degree element and confirm reduction keeps deg < φ(n).
        let n = 7_u32; // φ(7) = 6
        let big = CycInt::new(n, vec![1, 1, 1, 1, 1, 1, 1, 1, 1, 1]);
        assert!(big.coeffs().len() <= 6, "got {:?}", big.coeffs());
    }

    // -- sentinel-m2 promotion ----------------------------------------------

    #[test]
    fn sentinel_constants_have_order_zero() {
        assert_eq!(CycInt::zero().order(), SENTINEL);
        assert_eq!(CycInt::from_int(5).order(), SENTINEL);
        assert_eq!(CycInt::from_int(-3).order(), SENTINEL);
    }

    #[test]
    fn sentinel_promotes_on_add() {
        // from_int(2) + ζ_7  must live in field 7.
        let two = CycInt::from_int(2);
        let zeta = CycInt::zeta(7);
        let sum = two.add(&zeta);
        assert_eq!(sum.order(), 7);
        assert_eq!(sum, CycInt::new(7, vec![2, 1]));
        // Commutativity of promotion.
        let sum2 = zeta.add(&two);
        assert_eq!(sum, sum2);
    }

    #[test]
    fn sentinel_promotes_on_mul() {
        // from_int(3) · ζ_8 = 3ζ_8, in field 8.
        let three = CycInt::from_int(3);
        let zeta = CycInt::zeta(8);
        let prod = three.mul(&zeta);
        assert_eq!(prod.order(), 8);
        assert_eq!(prod, CycInt::new(8, vec![0, 3]));
        // The reverse direction must agree.
        assert_eq!(zeta.mul(&three), prod);
    }

    #[test]
    fn sentinel_plus_sentinel_stays_sentinel() {
        let a = CycInt::from_int(2);
        let b = CycInt::from_int(5);
        let s = a.add(&b);
        assert_eq!(s.order(), SENTINEL);
        assert_eq!(s, CycInt::from_int(7));
        let m = a.mul(&b);
        assert_eq!(m.order(), SENTINEL);
        assert_eq!(m, CycInt::from_int(10));
    }

    #[test]
    fn from_int_one_is_multiplicative_identity_in_field() {
        let one = CycInt::from_int(1);
        let e = CycInt::new(7, vec![0, 0, 0, 1, 1]);
        assert_eq!(one.mul(&e), e);
        assert_eq!(e.mul(&one), e);
    }

    #[test]
    #[should_panic(expected = "cannot combine CycInt of order")]
    fn mixing_distinct_fields_panics() {
        let a = CycInt::zeta(7);
        let b = CycInt::zeta(8);
        let _ = a.add(&b);
    }

    // -- RootCoeff basics ----------------------------------------------------

    #[test]
    fn zero_and_is_zero() {
        assert!(CycInt::zero().is_zero());
        assert!(!CycInt::from_int(1).is_zero());
        assert!(CycInt::from_int(0).is_zero());
        // ζ - ζ = 0
        let zeta = CycInt::zeta(7);
        assert!(zeta.sub(&zeta).is_zero());
    }

    #[test]
    fn neg_roundtrip() {
        let e = CycInt::new(8, vec![-2, -1, 0, 1]);
        assert_eq!(e.neg().neg(), e);
        assert_eq!(e.add(&e.neg()), CycInt::zero());
    }

    #[test]
    fn is_nonneg_on_constants() {
        assert!(CycInt::from_int(0).is_nonneg());
        assert!(CycInt::from_int(5).is_nonneg());
        assert!(!CycInt::from_int(-1).is_nonneg());
    }

    #[test]
    fn is_nonneg_on_field_values() {
        // 2cos(π/7) ≈ 1.80 > 0
        assert!(CycInt::two_cos_pi_over_m(7).is_nonneg());
        // negate it → negative
        assert!(!CycInt::two_cos_pi_over_m(7).neg().is_nonneg());
        // ζ_8 + ζ_8^{-1} = 2cos(π/4) = √2 > 0
        let zeta = CycInt::zeta(8);
        let zinv = CycInt::new(8, super::unit_pow(7, 8));
        assert!(zeta.add(&zinv).is_nonneg());
    }

    #[test]
    fn sqrt_two_squares_to_two() {
        // ζ_8 − ζ_8^3 is the positive square root of 2 (PyCox rootof1 docstring).
        let zeta = CycInt::zeta(8);
        let z3 = CycInt::new(8, super::unit_pow(3, 8));
        let x = zeta.sub(&z3);
        assert!(x.is_nonneg());
        assert_eq!(x.mul(&x), CycInt::from_int(2));
        assert!((x.approx() - 2.0_f64.sqrt()).abs() < 1e-12);
    }
}
