//! rustcox-core: Kazhdan-Lusztig polynomials and cells for finite Coxeter
//! groups. A Rust port of PyCox (M. Geck), verified against golden data
//! generated by the vendored reference in `pycox-ref/`.
//!
//! Implementation plan: `docs/superpowers/plans/2026-06-10-rustcox-implementation.md`.

// Modules land task by task; see the implementation plan.
pub mod bruhat;
pub mod cartan;
pub(crate) mod cartan_cyc;
pub mod element;
pub mod enumerate;
pub mod group;
pub mod io;
pub mod kl;
pub mod laurent;
pub mod ring;
pub mod roots;
pub mod wgraph;
