//! rustcox-core: Kazhdan-Lusztig polynomials and cells for finite Coxeter
//! groups. A Rust port of PyCox (M. Geck), verified against golden data
//! generated by the vendored reference in `pycox-ref/`.
//!
//! Implementation plan: `docs/superpowers/plans/2026-06-10-rustcox-implementation.md`.

// Modules land task by task; see the implementation plan.
pub mod laurent;
pub mod ring;
